spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  datasource:
    url: jdbc:mysql://localhost:3306/general_store_db
    username: root
    password: Gg7771999
    tomcat:
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=2,logFailed=true)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        session:
          events:
            log:
              QUERIES_SLOWER_THAN_MS: 10
  flyway:
    baselineOnMigrate: true
jwt:
  publicKey: classpath:app.pub
  privateKey: classpath:app.key
logging:
  level:
    org:
      springframework:
        orm.jpa: TRACE
folder:
  product: C:\Users\Kuba\OneDrive\Pictures\GeneralStorePhotos
info:
  version: "@pom.version@"
---
spring:
  config:
    activate:
      on-profile: mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: jakub.badzioch.main@gmail.com
    password: znlnboojwymcyhkt
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true